version: "3.3"
services:
  www:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MYSQL_HOST=10.5.0.6
      - MYSQL_USER=pwnuser
      - MYSQL_PASSWORD=pwnpass1337)(
      - MYSQL_DB=pwn
    volumes:
      - ./app:/var/www/html/
    ports:
      - "127.0.0.1:7337:80"
    container_name: pwnthis_www
    links:
      - db
    depends_on:
      - db
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass1337()
      - MYSQL_USER=pwnuser
      - MYSQL_PASSWORD=pwnpass1337)(
      - MYSQL_DATABASE=pwn
    container_name: pwnthis_db
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    ports: 
      - '127.0.0.1:3306:3306'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
volumes:
  persistent:
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
