version: "3.3"
services:
  www:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MYSQL_HOST=127.0.0.1
      - MYSQL_USER=pwnuser
      - MYSQL_PASSWORD=pwnpass1337)(
      - MYSQL_DB=pwn
    volumes:
      - ./app:/var/www/html/
    ports:
      - "7337:80"
    container_name: pwnthis_www
    depends_on:
      - db
    networks: 
      - default
  db:
    image: mysql:5.7
    restart: always
    command: [--default-authentication-plugin=mysql_native_password]
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass1337()
      - MYSQL_USER=pwnuser
      - MYSQL_PASSWORD=pwnpass1337)(
      - MYSQL_DATABASE=pwn
    container_name: pwnthis_db
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    ports: 
      - '3306:3306'
    networks: 
      - default
volumes:
  persistent: